status = ['ci/circleci%']
pr_status = [
    'ci/circleci: test_foo'
]
block_labels = ["DO NOT MERGE", "duplicate"]

[committer]
name = "King Ban"
email = "ban@example.com"
delete_merged_branches = true
