version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image
jobs:
  test_icle_helper:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: python -m unittest test_me.py
  am_i_still_there:
    docker:
      - image: circleci/python
    steps:
      - run: "false"

workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build
      - test_icle_helper
      - am_i_still_there
